### ISSUE TITLE
Better integration

### ISSUE THREAD

**Issue by andi-bute** [emotionLoop/visualCaptcha-meteorite#1]
Hi,
I've had to use captcha for a client and this was the only package.
It didn't work for me, paths are hardcoded, uses a different port, had problems with building.
So I made a new one, based on your work. I was in a rush so I didn't fork yours to do a pull request afterwards. This also means it's not all that clean right now, had to deliver fast. You can check it out at https://github.com/andi-bute/captcha-meteor

**Comment by BrunoBernardino** [comment]
Hi @andi-bute I'm sorry but we've deprecated this package for visualCaptcha. Feel free to fork/submit a PR.
